apiVersion: v1
kind: Service
metadata:
  name: central-base-station-service
spec:
  selector:
    app: central-base-station
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

