apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-processor-deployment
  labels:
    component: kafka-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-processor-deployment
  template:
    metadata:
      labels:
        component: kafka-processor-deployment
    spec:
      containers:
        - name: kafka-processor-container
          image: kafka-processor:latest  # Your local image name
          imagePullPolicy: Never
          env:
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"  # Memory settings
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
